# This is the default format.
# For more see: http://jekyllrb.com/docs/permalinks/
permalink: /:title
# https://help.github.com/articles/migrating-your-pages-site-from-maruku
markdown: redcarpet

highlighter: pygments
paginate: 20 # pagination based on number of posts
paginate_path: "page/:num"

# These paths are to the main pages Jekyll-Bootstrap ships with.
# Some JB helpers refer to these paths; change them here if needed.
#
categories_path : categories.html
tags_path : tags.html

#BASE_PATH : http://blog.ankanbiswas.in/uno-dbyll
BASE_PATH :

description : 从前种种譬如昨日死，以后种种譬如今日生
title : Spring
logo : 
#cover : /assets/images/background-cover.jpg


author:
  name: 
  maxim: Stay hungry,Stay foolish
  role: 
  email: 
  github: 
  twitter: 
  facebook: 
  googleplus: 
  bio: ""
  uno-dbyll: 
